### PR TITLE
Format, PEPify and improve Python 2/3 compatibility

### PR DESCRIPTION
**Pull request by kirillbobyrev**
This patch does not introduce any functionality changes. Instead, it focuses on PEP compliance (mostly solving line width limit violations and unused imports) and Python 2/3 compatibility (mostly wrapping `print`s into braces and using Python 3's `range`).

### CODE REVIEW

**Comment by kirillbobyrev** [comment]
NOTE: I should also replace Python 2's division with `//` for it to run smoothly.

**Comment by kirillbobyrev** [comment]
Apparently, `2to3` tool doesn't handle integer division and therefore it has to be handled manually.

**Comment by natanielruiz** [comment]
Hey! This is very cool. Let me test it and then I'll merge it.

**Comment by kirillbobyrev** [comment]
@natanielruiz This is just about Python 2/3; I'm using PyTorch 1.0.1 - there are couple deprecation warnings, but nothing major.

I suspect I should change Python 2 integer division to Python 3's (guidelines say one should use `//` in Python 2, too, regardless of the same effect) in several files, but I will probably get back to it later this week.

**Pull request closed without merging**
